@startuml

class CouchdbRasFileSystemProvider{

}

class CouchdbRasWriteByteChannel {

}


CouchdbRasFileSystemProvider -> CouchdbRasWriteByteChannel : "creates"
CouchdbRasStore -> CouchdbRasFileSystemProvider : "creates"
@enduml