ARG dockerRepository
ARG tag
FROM ${dockerRepository}/galasadev/galasa-framework:${tag}

COPY repo/ /usr/local/apache2/htdocs/
COPY extensions.githash /usr/local/apache2/htdocs/extensions.githash