ARG dockerRepository
ARG tag
FROM ${dockerRepository}/galasa-dev/framework-maven-artefacts:${tag}

COPY repo/ /usr/local/apache2/htdocs/
COPY extensions.githash /usr/local/apache2/htdocs/extensions.githash