// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalasaEcosystem) DeepCopyInto(out *GalasaEcosystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalasaEcosystem.
func (in *GalasaEcosystem) DeepCopy() *GalasaEcosystem {
	if in == nil {
		return nil
	}
	out := new(GalasaEcosystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GalasaEcosystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalasaEcosystemList) DeepCopyInto(out *GalasaEcosystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GalasaEcosystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalasaEcosystemList.
func (in *GalasaEcosystemList) DeepCopy() *GalasaEcosystemList {
	if in == nil {
		return nil
	}
	out := new(GalasaEcosystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GalasaEcosystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalasaEcosystemSpec) DeepCopyInto(out *GalasaEcosystemSpec) {
	*out = *in
	in.Propertystore.DeepCopyInto(&out.Propertystore)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalasaEcosystemSpec.
func (in *GalasaEcosystemSpec) DeepCopy() *GalasaEcosystemSpec {
	if in == nil {
		return nil
	}
	out := new(GalasaEcosystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalasaEcosystemStatus) DeepCopyInto(out *GalasaEcosystemStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalasaEcosystemStatus.
func (in *GalasaEcosystemStatus) DeepCopy() *GalasaEcosystemStatus {
	if in == nil {
		return nil
	}
	out := new(GalasaEcosystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyStoreCluster) DeepCopyInto(out *PropertyStoreCluster) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.InitProps != nil {
		in, out := &in.InitProps, &out.InitProps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyStoreCluster.
func (in *PropertyStoreCluster) DeepCopy() *PropertyStoreCluster {
	if in == nil {
		return nil
	}
	out := new(PropertyStoreCluster)
	in.DeepCopyInto(out)
	return out
}
