// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiServer) DeepCopyInto(out *ApiServer) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiServer.
func (in *ApiServer) DeepCopy() *ApiServer {
	if in == nil {
		return nil
	}
	out := new(ApiServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EngineController) DeepCopyInto(out *EngineController) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EngineController.
func (in *EngineController) DeepCopy() *EngineController {
	if in == nil {
		return nil
	}
	out := new(EngineController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalasaEcosystem) DeepCopyInto(out *GalasaEcosystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalasaEcosystem.
func (in *GalasaEcosystem) DeepCopy() *GalasaEcosystem {
	if in == nil {
		return nil
	}
	out := new(GalasaEcosystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GalasaEcosystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalasaEcosystemList) DeepCopyInto(out *GalasaEcosystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GalasaEcosystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalasaEcosystemList.
func (in *GalasaEcosystemList) DeepCopy() *GalasaEcosystemList {
	if in == nil {
		return nil
	}
	out := new(GalasaEcosystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GalasaEcosystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalasaEcosystemSpec) DeepCopyInto(out *GalasaEcosystemSpec) {
	*out = *in
	in.Propertystore.DeepCopyInto(&out.Propertystore)
	in.APIServer.DeepCopyInto(&out.APIServer)
	in.RasSpec.DeepCopyInto(&out.RasSpec)
	in.EngineController.DeepCopyInto(&out.EngineController)
	in.EngineResmon.DeepCopyInto(&out.EngineResmon)
	in.Simbank.DeepCopyInto(&out.Simbank)
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalasaEcosystemSpec.
func (in *GalasaEcosystemSpec) DeepCopy() *GalasaEcosystemSpec {
	if in == nil {
		return nil
	}
	out := new(GalasaEcosystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalasaEcosystemStatus) DeepCopyInto(out *GalasaEcosystemStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalasaEcosystemStatus.
func (in *GalasaEcosystemStatus) DeepCopy() *GalasaEcosystemStatus {
	if in == nil {
		return nil
	}
	out := new(GalasaEcosystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoring) DeepCopyInto(out *Monitoring) {
	*out = *in
	if in.MetricsReplicas != nil {
		in, out := &in.MetricsReplicas, &out.MetricsReplicas
		*out = new(int32)
		**out = **in
	}
	if in.PrometheusReplicas != nil {
		in, out := &in.PrometheusReplicas, &out.PrometheusReplicas
		*out = new(int32)
		**out = **in
	}
	if in.GrafanaReplicas != nil {
		in, out := &in.GrafanaReplicas, &out.GrafanaReplicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoring.
func (in *Monitoring) DeepCopy() *Monitoring {
	if in == nil {
		return nil
	}
	out := new(Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyStoreCluster) DeepCopyInto(out *PropertyStoreCluster) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.InitProps != nil {
		in, out := &in.InitProps, &out.InitProps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyStoreCluster.
func (in *PropertyStoreCluster) DeepCopy() *PropertyStoreCluster {
	if in == nil {
		return nil
	}
	out := new(PropertyStoreCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RasSpec) DeepCopyInto(out *RasSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RasSpec.
func (in *RasSpec) DeepCopy() *RasSpec {
	if in == nil {
		return nil
	}
	out := new(RasSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceMonitor) DeepCopyInto(out *ResourceMonitor) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceMonitor.
func (in *ResourceMonitor) DeepCopy() *ResourceMonitor {
	if in == nil {
		return nil
	}
	out := new(ResourceMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Simbank) DeepCopyInto(out *Simbank) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Simbank.
func (in *Simbank) DeepCopy() *Simbank {
	if in == nil {
		return nil
	}
	out := new(Simbank)
	in.DeepCopyInto(out)
	return out
}
